# Generated by Django 4.2.1 on 2023-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('class_level', models.CharField(max_length=50)),
                ('gpa', models.CharField(max_length=50)),
            ],
        ),
    ]
